// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlj-E8onDBv_wEMaE2zwWuZT2G5xfHf0',
    appId: '1:1019426616177:web:cdb88f0b73e2eee5f5fcd0',
    messagingSenderId: '1019426616177',
    projectId: 'fir-auth-6a5b0',
    authDomain: 'fir-auth-6a5b0.firebaseapp.com',
    storageBucket: 'fir-auth-6a5b0.appspot.com',
    measurementId: 'G-HL32TLS3EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-Nch4VUlsBt6U6Q3VQ1SJnl-I09PR8k',
    appId: '1:1019426616177:android:b4d04cd526d75cc5f5fcd0',
    messagingSenderId: '1019426616177',
    projectId: 'fir-auth-6a5b0',
    storageBucket: 'fir-auth-6a5b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7hPzlqYHUiru7ukOyUh8-Dz8FpxDwdkk',
    appId: '1:1019426616177:ios:596d16a3d86aab60f5fcd0',
    messagingSenderId: '1019426616177',
    projectId: 'fir-auth-6a5b0',
    storageBucket: 'fir-auth-6a5b0.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7hPzlqYHUiru7ukOyUh8-Dz8FpxDwdkk',
    appId: '1:1019426616177:ios:596d16a3d86aab60f5fcd0',
    messagingSenderId: '1019426616177',
    projectId: 'fir-auth-6a5b0',
    storageBucket: 'fir-auth-6a5b0.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDlj-E8onDBv_wEMaE2zwWuZT2G5xfHf0',
    appId: '1:1019426616177:web:73d0b14bfc3bb561f5fcd0',
    messagingSenderId: '1019426616177',
    projectId: 'fir-auth-6a5b0',
    authDomain: 'fir-auth-6a5b0.firebaseapp.com',
    storageBucket: 'fir-auth-6a5b0.appspot.com',
    measurementId: 'G-ZVX58SSF3G',
  );
}
