// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIUW8g6G9NpBRR2Fq51nZLM0avi7X98CA',
    appId: '1:859539264333:web:89376c7f7919d53d875d04',
    messagingSenderId: '859539264333',
    projectId: 'fir-auth-project-c2516',
    authDomain: 'fir-auth-project-c2516.firebaseapp.com',
    storageBucket: 'fir-auth-project-c2516.appspot.com',
    measurementId: 'G-R6ZYS5CQTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyF8RrzldsztHSE4eEk0ccewwrvzh0XW8',
    appId: '1:859539264333:android:2342eea956ecb930875d04',
    messagingSenderId: '859539264333',
    projectId: 'fir-auth-project-c2516',
    storageBucket: 'fir-auth-project-c2516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAjqHtEie73x5D0YUcYbTD2hpjWw-2S8o',
    appId: '1:859539264333:ios:cd8371b14aae16cf875d04',
    messagingSenderId: '859539264333',
    projectId: 'fir-auth-project-c2516',
    storageBucket: 'fir-auth-project-c2516.appspot.com',
    iosBundleId: 'com.example.firebaseAuthProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAjqHtEie73x5D0YUcYbTD2hpjWw-2S8o',
    appId: '1:859539264333:ios:cd8371b14aae16cf875d04',
    messagingSenderId: '859539264333',
    projectId: 'fir-auth-project-c2516',
    storageBucket: 'fir-auth-project-c2516.appspot.com',
    iosBundleId: 'com.example.firebaseAuthProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIUW8g6G9NpBRR2Fq51nZLM0avi7X98CA',
    appId: '1:859539264333:web:67a6ebd3e2b8b3c9875d04',
    messagingSenderId: '859539264333',
    projectId: 'fir-auth-project-c2516',
    authDomain: 'fir-auth-project-c2516.firebaseapp.com',
    storageBucket: 'fir-auth-project-c2516.appspot.com',
    measurementId: 'G-WDY30C43KZ',
  );
}
